language: node_js
node_js: lts/*
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-unstable
cache:
  yarn: true
  directories:
    - node_modules
    - bower_components
    - .eslintcache
    - $HOME/.cache/bower
    - $HOME/cc
env:
  global:
    - CC_TEST_REPORTER_ID=ee7700d6670416f453c04be8c8ea32b756b7309ce33bf965402136f5d4fb91bc
    - SAUCE_USERNAME=nomego
    - secure: BxvbM9LnQsXLoaohrIf+ip1kSVmqTgqOxwGU7HZnaw3hOjOZ5PGaD2l1G9X0j2c4QysB6KLcbmrJDWkIVtpiIR2NgC9DQbDpgCyafO+DXk6+sVOuGuV1h/5yt+rfx+VZOItkfCcmsi0MgUjCNCpk22lHIwDbRY3+vvRNNgF8eyyCMz47N+TBzpinTohU0xZOpWHPQbFQ6TfR6heoV/DrF/XPkDbDDLU4WV9AWrPZk9dHzLZLbl5DyXwWivyNqSCkPQCBhYckqZRuMU0XWNlp2tuxC+UMjBDh9HFWl4swZfcrBPOUE0zhjxKBF88QzJyfsLNd5pvkJNKYeQsLZ9z0I47INX867ZGi2iIAX4JW1I4FbAwZs8YnCMAKUzOdJgF8WkvjWRFZ+teO8Wp8s+ymb5NZYMaXlbVjg2wVYau3+1agLhhNXwVv7vYAfLclLfXHKrRCPeSBkX7iVUwlOn5OemWNJBJ9eGCqYi/mbU900wIdk00g9nyZeEjwtbWZkjrMprWqQkCPWxA5ZmkLWlm1pkduokUx0LlCV5MigOgJkQb//OacYwLjIdJCKX/V/KOipCCAlWBaVh3cFBQAx3EcPelD1nWT07xQtcz/BwrmvMGaNnQln3RvuOAV3oRfltR1EDIcRStoDNz00Evc5+Q1DL4fkHnMYWYFsfIQorlb+6o=
    - 'NEO_CC_URL=https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64'
    - NEO_CC=$HOME/cc/cc-test-reporter
    - LAUNCHPAD_CHROME=/usr/bin/google-chrome-unstable
before_script:
  - yarn lint
  - '([[ -e $NEO_CC ]] || curl -L $NEO_CC_URL > $NEO_CC) && chmod +x $NEO_CC'
  - $NEO_CC before-build
script:
  - 'yarn test $([ -z "$SAUCE_ACCESS_KEY" ] && echo "--skip-plugin sauce")'
  - $NEO_CC after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  slack:
    secure: iiQaiEb8Zn1chQAfKDunAAIbXGEyTl723zJPYNz1WecSbMTtEIiCbACT/H5nOA8NbYLhkYVuMmBXgqyvctas3JiZ1cvueTua571Qb2ryhB0eqr0qslJOCj0N+uBpnfst5DwoUV2FkuQcwm0V4ExzXV3e78gRFeHqRhHo2KX4AcNrAL5Qydn74rFcTreAAsgj7PR/2eoPyBUBlzGb+Wb0ytPoDNbT4+Tw/8KDxRXahSUEgaJ2F/MkC0Kk2lGHkDFFkAwtTsqjASKUVyvjc4cuNuBIMIS528LmtKVYZBoOhrU0Yuxstg+sgo77mo8QMRkmp0P/u48dQZZJGhcUnoNbpMdMNyQq5TzoS98GzjPf4zeTsCtQyGW+ku36ofmDvIQLK3GD4nSAB9KrJQ0T5V8kgflSkYCnUqywDAmSkwG8eaUZZWKJX8wf5uEv2vOzrlYQCkf44j85msteF54QGcO7Nyb0b/eRuWPIX6Y9JAs397o6Be9MjL/uMbbMTAVsmfXQr69i9s75Sw3ARGZMhY7vQequbfqtnBPpsGp1qwHZqesOC5GHzjki+9+uyk9ypVE7PJTSR6908OC7ShV7SpX3+89i5kWZkEMmY8JxULEhmnNokWHMWM1qBCCZR+nGfak/aLBsT/xUjMw8UhGBIIdngVHTZaMT1meMob6DRpxvePs=

