language: node_js
node_js: 6
dist: trusty
sudo: required
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  yarn: true
  directories:
    - node_modules
    - bower_components
    - .eslintcache
    - $HOME/.cache/bower
before_script:
  - yarn run lint
script:
  - xvfb-run yarn test
notifications:
  slack:
    secure: iiQaiEb8Zn1chQAfKDunAAIbXGEyTl723zJPYNz1WecSbMTtEIiCbACT/H5nOA8NbYLhkYVuMmBXgqyvctas3JiZ1cvueTua571Qb2ryhB0eqr0qslJOCj0N+uBpnfst5DwoUV2FkuQcwm0V4ExzXV3e78gRFeHqRhHo2KX4AcNrAL5Qydn74rFcTreAAsgj7PR/2eoPyBUBlzGb+Wb0ytPoDNbT4+Tw/8KDxRXahSUEgaJ2F/MkC0Kk2lGHkDFFkAwtTsqjASKUVyvjc4cuNuBIMIS528LmtKVYZBoOhrU0Yuxstg+sgo77mo8QMRkmp0P/u48dQZZJGhcUnoNbpMdMNyQq5TzoS98GzjPf4zeTsCtQyGW+ku36ofmDvIQLK3GD4nSAB9KrJQ0T5V8kgflSkYCnUqywDAmSkwG8eaUZZWKJX8wf5uEv2vOzrlYQCkf44j85msteF54QGcO7Nyb0b/eRuWPIX6Y9JAs397o6Be9MjL/uMbbMTAVsmfXQr69i9s75Sw3ARGZMhY7vQequbfqtnBPpsGp1qwHZqesOC5GHzjki+9+uyk9ypVE7PJTSR6908OC7ShV7SpX3+89i5kWZkEMmY8JxULEhmnNokWHMWM1qBCCZR+nGfak/aLBsT/xUjMw8UhGBIIdngVHTZaMT1meMob6DRpxvePs=
